// GENERATED BY scripts/build-registry.ts - DO NOT EDIT.
import * as React from "react"

export const Index: Record<
  string,
  { name: string; component: React.LazyExoticComponent<React.ComponentType> }
> = {
  "button-demo": {
    name: "button-demo",
    component: React.lazy(() => import("@/registry/fujin/examples/button-demo")),
  },
  "field-demo": {
    name: "field-demo",
    component: React.lazy(() => import("@/registry/fujin/examples/field-demo")),
  },
}
